AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Execute trades against IG Exchange
Resources:
  trading:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 256
      CodeUri: ./
      Environment:
        Variables:
          IG_TOKENS_EXP: ""
          IG_XST: ""
          IG_CST: ""
          IG_LIGHTSTREAMER_END_POINT: ""
          X_REQUEST_ID: ""
          CURRENT_ACCOUNT_ID: ""
      Events:
        RunWhenMessageInQueue:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:ap-southeast-2:023075176548:orders
            BatchSize: 10
